import React from 'react';
import L1_1 from '/public/assets/L1-1.png';
import L1_2 from '/public/assets/L1-2.png';
import L1_3 from '/public/assets/L1-3.png';
import L1_4 from '/public/assets/L1-4.png';

const pattern = `
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB
BBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BAAAAAAAAAAAAAAAAAAAAAAAAAADDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BAAAAAAAAAAAAAAAAAAAAAAAAAADDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBB
BAAAAAAAAAAAAAAAAAABCCCCCCCCCCCCCCCCCCCCCBAAAAAAAAAAAAAAAAAAAAAB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
`;

export const getAssetByChar = (char: string): string | undefined => {
  switch (char) {
    case 'A': return L1_1;
    case 'B': return L1_2;
    case 'C': return L1_3;
    case 'D': return L1_4;
    default: return undefined;
  }
}

const Lsize1: React.FC = () => {
  const rows = pattern.trim().split('\n');

  return (
    <div className="pattern-container">
      {rows.map((row, rowIndex) => (
        <div className="pattern-row" key={`row-${rowIndex}`}>
          {Array.from(row).map((char, colIndex) => (
            <img
              key={`img-${rowIndex}-${colIndex}`}
              src={getAssetByChar(char)}
              alt={char}
              className={`pattern-char pattern-char-${char}`}
            />
          ))}
        </div>
      ))}
    </div>
  );
}

export default Lsize1;
